# Generated by Django 5.1.4 on 2024-12-08 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haha', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cipher',
            old_name='text',
            new_name='text_cipher',
        ),
    ]
